#
# This source file is part of the PAWS application based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

default_platform(:ios)

platform :ios do
  before_all do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "5"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "6"
  end

  desc "Build and test"
  lane :test do
    run_tests(
      skip_build: true,
      derived_data_path: ".derivedData",
      code_coverage: true,
      devices: ["iPhone 15 Pro"],
      force_quit_simulator: true,
      reset_simulator: true,
      prelaunch_simulator: false,
      concurrent_workers: 1,
      max_concurrent_simulators: 1,
      result_bundle: true,
      output_directory: ".",
      xcargs: "-skipPackagePluginValidation -skipMacroValidation"
    )
  end

  desc "Screenshots"
  lane :screenshots do
    run_tests(
      destination: "generic/platform=iOS Simulator",
      configuration: "Debug",
      derived_data_path: ".derivedData",
      xcargs: "-skipPackagePluginValidation -skipMacroValidation",
      build_for_testing: true
    )

    snapshot(
      test_without_building: true,
      derived_data_path: ".derivedData",
      devices: [
        "iPhone 15 Pro",
        "iPhone SE (3rd generation)"
      ],
      languages: [
         "en-US",
      ],
      scheme: "PAWS",
      output_directory: "./fastlane/screenshots",
      clear_previous_screenshots: true,
      concurrent_simulators: false,
      stop_after_first_error: true,
      skip_open_summary: true
    )
    
    # Workaround for https://github.com/fastlane/fastlane/issues/21759 and 
    Dir.glob("./screenshots/**/iPhone 15 Pro-*.png").each do |file|
      sh("sips --resampleHeightWidth 2778 1284 '#{file}'")
    end

    # Scale to 1242 x 2208 as there are no iOS 18 Simulators supporting this screen size.
    Dir.glob("./screenshots/**/iPhone SE (3rd generation)-*.png").each do |file|
      sh("sips --resampleHeightWidth 2208 1242 '#{file}'")
    end
  end

  desc "Build app"
  lane :build do
    build_app(
      skip_archive: true,
      skip_codesigning: true,
      derived_data_path: ".derivedData",
      xcargs: "-skipPackagePluginValidation -skipMacroValidation"
    )
  end

  desc "Archive app"
  lane :archive do
    build_app(
      derived_data_path: ".derivedData",
      xcargs: "-skipPackagePluginValidation -skipMacroValidation",
      export_options: {
        provisioningProfiles: {
          "edu.stanford.cs342.2023.paws" => "CS342 2023 PAWS"
        }
      }
    )
  end

  desc "Sign in to the App Store Connect API"
  lane :signin do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_BASE64"],
      is_key_content_base64: true
    )
  end

  desc "Publish a release to TestFlight or the App Store depending on the environment"
  lane :deploy do |options|
    environment = options[:environment] || "staging"

    signin

    if environment == "production"
      unless app_in_review
        screenshots
      end
    end

    increment_build_number(
      {
        build_number: latest_testflight_build_number + 1
      }
    )
    archive
    commit = last_git_commit
    
    if environment == "production"
      deliver(
        submit_for_review: true,
        force: true,
        overwrite_screenshots: !app_in_review?,
        automatic_release: true,
        precheck_include_in_app_purchases: false,
        metadata_path: "./fastlane/metadata",
        screenshots_path: "./fastlane/screenshots"
      )
    else
      upload_to_testflight(
        distribute_external: true,
        groups: [
          "External Testers"
        ],
        submit_beta_review: true,
        notify_external_testers: true,
        changelog: commit[:message]
      )
    end
  end

  lane :test_app_in_review do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_BASE64"],
      is_key_content_base64: true
    )
    
    UI.message("Calling app_in_review lane directly")
    if app_in_review
      UI.message("True")
    else
      UI.message("False")
    end
  end

  private_lane :app_in_review do
    UI.message("Starting app_in_review? lane")
  
    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    UI.message("App Identifier: #{app_identifier}")
  
    app = Spaceship::ConnectAPI::App.find(app_identifier)
    UI.message("Found app: #{app.name}")
  
    version = app.get_live_app_store_version || app.get_edit_app_store_version
    UI.message("App version: #{version.version_string}")
  
    review_status = version.app_store_state
    UI.message("App review status: #{review_status}")
  
    in_review = review_status == 'WAITING_FOR_REVIEW' || review_status == 'IN_REVIEW'
    UI.message("Is the app in review? #{in_review}")
  
    in_review
  end
end
