#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2024 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

# A list of devices you want to take the screenshots from
devices([
  "iPhone 15 Pro Max",
  "iPhone 14 Plus",
  "iPhone 8 Plus",
])

languages([
  "en-US",
])

# The name of the scheme which contains the UI Tests
scheme("PAWS")

# Where should the resulting screenshots be stored?
output_directory("./.screenshots")

clear_previous_screenshots(true)

erase_simulator(true)

# Set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
launch_arguments(["--showOnboarding", "--useFirebaseEmulator"])

# For more information about all available options run
# fastlane action snapshot
