#
# This source file is part of the CS342 2023 PAWS Team Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
  buildandtest:
    name: Build and Test
    uses: CS342/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      codeql: true
      artifactname: PAWS.xcresult
      setupfirebaseemulator: true
      customcommand: "firebase emulators:exec 'fastlane test'"
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: buildandtest
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: PAWS.xcresult
