#
# This source file is part of the PAWS application based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Production Deployment

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deployment:
    name: Production Deployment
    uses: ./.github/workflows/beta-deployment.yml
    permissions:
      contents: read
      actions: read
      security-events: write
    secrets: inherit
    with:
      environment: production
